### PR TITLE
Emit disconnects

### PR DESCRIPTION
**Pull request by pgebheim**
Call disconnect listeners when a disconnect event is detected by an attempted call.

### CODE REVIEW

**Comment by epheph** [comment]
lgtm, (aside from lint errors)

**Comment by MicahZoltu** [comment]
@tinybike We should get more people than just me merge rights to this repo.

**Comment by holgerd77** [comment]
@MicahZoltu I can also look into PRs here every now and then (and have merge rights). Was just not sure till now if this is ok, since you guys seemed pretty active on this.

**Comment by MicahZoltu** [comment]
@holgerd77 Ah, I totally forgot this was in `ethereumjs` and not `AugurProject`.  😄 My comment to Jack was more meant that Augur should make sure others besides me can merge PRs in this repo since the Augur dev team are the active developers and I'm transitioning off the team soon.  😄

**Pull request merged**
