### PR TITLE
change how test is fixed

### PR DESCRIPTION
**Pull request by epheph**
Re #119

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Doesn't this put the Node 6 failure back in?  Per our conversation, my vote would be to drop node 6 support as it is nearing end of life anyway.

Also consider dropping a console.log of the block in the callback to see if it is getting called back twice for the same log.

**Comment by epheph** [comment]
#118 goes with it, prolly should have made them same PR.

**Comment by petong** [comment]
@MicahZoltu is this safe to merge?

**Comment by MicahZoltu** [comment]
Based on comments (which I don't remember the context of) it appears that node6 support is dropped, so this is fine now?

**Pull request merged**
