### PR TITLE
Automatically use eth_estimateGas to set default gas

### PR DESCRIPTION
**Pull request by tinybike**
Story details: https://app.clubhouse.io/augur/story/10940

### CODE REVIEW

**Comment by epheph** [comment]
I had to back out this change, i was getting this error during deploy to local geth docker:

```connected to ethereum
universe: 0x8062da104239cf70c76b77c61ea988bf6382736a
[ethrpc] eth_subscribe request failed, fall back to polling for blocks: notifications not supported
reputationToken: 0x1b8dae4f281a437e797f6213c6564926a04d9959
transaction failed: { Error: gas required exceeds allowance or always failing transaction
    at parseEthereumResponse (/augur.js/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:7)
    at errorHandler (/augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:43:16)
    at /augur.js/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:54:7
    at store.dispatch (/augur.js/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/augur.js/node_modules/ethrpc/src/reset-state.js:45:9)
    at HttpTransport.<anonymous> (/augur.js/node_modules/ethrpc/src/transport/http-transport.js:54:12)
    at Request.self.callback (/augur.js/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7) code: -32000 } { constant: false,
  name: 'faucet',
  inputs: [ '_amount' ],
  signature: [ 'uint256' ],
  returns: 'bool',
  from: '0x913da4198e6be1d5f5e4a40d0667f70c0b5430eb',
  to: '0x1b8dae4f281a437e797f6213c6564926a04d9959',
  params:
   [ '0x00000000000000000000000000000000000000000000152d02c7e14af6800000' ],
  uuid: 'bb7b52e5-fc73-464a-8d02-ab020dd7c556',
  send: true } undefined 0x1614f1a22a5c586d33141f1f6830e53ded2c19d6e2522fc666e9fb0409402e2e
Failure!
 gas required exceeds allowance or always failing transaction
-------- BACKTRACE ------
Error: gas required exceeds allowance or always failing transaction
    at parseEthereumResponse (/augur.js/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)```

**Comment by epheph** [comment]
It could be #70 or #71 too, this just seems like most likely candidate

**Comment by tinybike** [comment]
@epheph how are you making that faucet request?  Are you using one of the scripts to do it, or using the UI?

**Comment by epheph** [comment]
I did so using the build/deploy process for the docker geth pops, so not the UI, kicked off via `dp`

**Comment by tinybike** [comment]
Hm, I just tested running `scripts/rep-faucet.js` in augur.js, and it completed successfully.

**Comment by tinybike** [comment]
@epheph did the failure happen on Rinkeby, or a local chain?  (If local, which one?)

**Comment by tinybike** [comment]
Note, it's possible that the failure is stochastic -- ethrpc currently adds an extra 25% gas to the transaction as a buffer, I haven't observed any not-enough-gas transaction failures at this rate but it's not impossible!

**Comment by tinybike** [comment]
@epheph can you paste a hash of one of your failing transactions here?  What does the receipt's `gasUsed` say?

**Pull request merged**
